### ISSUE TITLE
[BUG] SearchRequestBuilder.toString() makes JSON query string set by .setSource() method not working

### ISSUE THREAD

**Issue by cooniur** [elasticsearch/elasticsearch#9926] opened 2015-02-27 21:29 UTC
Related to: https://github.com/elasticsearch/elasticsearch/issues/9910

If you use JSON string as the query and set it by calling `setSource()` method, before executing the query if you call `requestBuilder.toString()` and then execute the query, you will get incorrect response, because `toString()` modified the internal state of `SearchRequestBuilder` object.

Try this code:

    @GrabResolver(name='maven', root='http://repo1.maven.org/maven2/')
	@Grab(group='org.elasticsearch', module='elasticsearch', version='1.4.4')
	import org.elasticsearch.common.settings.Settings
	import org.elasticsearch.common.settings.ImmutableSettings
	import org.elasticsearch.common.transport.InetSocketTransportAddress
	import org.elasticsearch.client.Client
	import org.elasticsearch.client.transport.TransportClient
	import org.elasticsearch.action.index.IndexRequestBuilder
	import org.elasticsearch.action.index.IndexResponse
	import org.elasticsearch.action.search.SearchRequestBuilder
	import org.elasticsearch.action.search.SearchResponse

	Settings settings = ImmutableSettings.settingsBuilder().put("cluster.name", "elasticsearch").build();
	Client client = new TransportClient(settings).addTransportAddress(new InetSocketTransportAddress("localhost", 9300));

	[1,2,3,4].each() {
	    String body = """{"name":"Hello world ${it}"}"""
	    IndexRequestBuilder indexRequestBuilder = new IndexRequestBuilder(client, "twitter")
	            .setType("data")
	            .setId(it.toString())
	            .setSource(body)
	            .setRefresh(true)
	    IndexResponse indexResponse = indexRequestBuilder.execute().actionGet()
	}

	String jsonQuery = """{"query":{"filtered":{"filter":{"term":{"_id":"1"}}}}}"""
	SearchRequestBuilder requestBuilder = client.prepareSearch("twitter")
	            .setTypes("data")
	            .setSource(jsonQuery)

	// This is the bug
	println requestBuilder.toString()

	SearchResponse response = requestBuilder.execute().actionGet()
	println response.toString()

The expected response is one document with `id=1`, however, the actual response is all documents inside the index.

But if you remove the bug line, the response will be correct.

**Comment by javanna** [comment] 2015-02-27 21:36
I think this is a duplicate of #5576. Can you confirm @cooniur please?

**Comment by cooniur** [comment] 2015-02-27 21:44
@javanna 
Yes, it is. By the way, I can't believe that this bug has been out there for almost one year. This bug is so hard to debug and caused a lot of confusion in our project.

Since normally people use `toString()` for debug purpose, the bug could be fixed by the following code at least:

    @Override
    public String toString() {
		if (sourceBuilder != null) {
			return sourceBuilder.toString();
		}

		if (request.source() != null) {
			return Arrays.toString(request.source().toBytes());
		}

		return "{ }";
    }

**Comment by javanna** [comment] 2015-02-27 21:47
I agree with you @cooniur . We've been working on it, there is a PR opened for it (#7334) but for some reason it is not merged yet. We just have to get it in, I am sorry it took so long.

Closing this issue as a duplicate, thanks for reporting though!

**Closed by javanna** 2015-02-27 21:47 UTC

**Comment by cooniur** [comment] 2015-02-27 21:48
@javanna 

Thanks! By the way, `setExtraSource()` is a workaround for this bug. But hopefully the PR can be merged soon.

Regards
