### ISSUE TITLE
No failover if number_of_replicas exceeds number of nodes

### ISSUE THREAD

**Issue by md126733** [elasticsearch/elasticsearch#9213] opened 2015-01-09 03:48 UTC
I have a 3-node cluster with the following settings:
   - index.number_of_shards=5
   - index.number_of_replicas=2 (for durability)
   - discovery.zen.minimum_master_nodes: 2

I'm finding that if I shut down 2 of the nodes, after setting minimum_master_nodes=1 on the remaining node and restarting, the cluster stays red with all shards unassigned.  They remain in the unassigned state until I manually reduce number_of_replicas to down 1 or 0.  Just wondering if this is a bug?  

See https://groups.google.com/forum/#!topic/elasticsearch/hXLr0PRzQYE for additional discussion/screenshots.

**Comment by md126733** [comment] 2015-01-09 03:53
NB I'm seeing this behaviour in ES 1.3.4 (jdk1.7.0_60)

**Comment by jprante** [comment] 2015-01-09 16:35
This is expected. 3 nodes can hold replica level 2. When 2 nodes are down, you can not match minimum_master_nodes and also not the index replica level and the cluster halts with health = red.  If you modify minimum_master_nodes, this sets cluster health to green but index health is still red. If you modify number_of_replicas to 1 or 0, this sets the index health to green, and this triggers cluster health to green.

**Comment by clintongormley** [comment] 2015-01-13 20:19
As @jprante explained, this is not a bug.  Closing

**Closed by clintongormley** 2015-01-13 20:19 UTC
