### ISSUE TITLE
Search SCAN and "regular" scrolling should behave the same

### ISSUE THREAD

**Issue by kimchy** [elasticsearch/elasticsearch#9326] opened 2015-01-16 01:47 UTC
For historic reasons, scan implementation returns first the count, and then the hits in subsequent requests. While scrolling with regular search returns the first N results immediately. 

It would be nice if SCAN behaved the same as regular scrolling? Maybe even automatically execute in "scan" mode if sort is set to an empty array or something like that, and scan search type is just a flavor on that?

**Comment by dadoonet** [comment] 2015-01-16 03:53
+1 it confuses users. See https://github.com/elasticsearch/elasticsearch/issues/6294

**Comment by clintongormley** [comment] 2015-01-16 11:19
Closing as duplicate of #2028

**Closed by clintongormley** 2015-01-16 11:19 UTC

**Comment by kul** [comment] 2015-01-22 07:17
+1
