### ISSUE TITLE
[JAVA-API] setSource has no effect on scroll search

### ISSUE THREAD

**Issue by kul** [elasticsearch/elasticsearch#6294] opened 2014-05-23 11:42 UTC
For the following fluent buildup i get 0 result for query `Q` which is proper query like `{"query" :....}`. But on replacing `setSource` with `setQuery` and removing the outer "query" form in json i get correct results!

Although it is ok as a workaround but this means i can not use sorting.

````java
client.prepareSearch("myindex").setSearchType(SearchType.SCAN)
  .setTypes("mytype").setScroll("1m").setSize(30).setSource(Q).execute().actionGet().getScrollId()
```
I am using scrollid from above to scroll further with
```java
client.prepareSearchScroll(scrollid).setScrol("1m").execute().actionGet()
```
Thanks

**Comment by dadoonet** [comment] 2015-01-02 16:44
Hi @kul 

I tried to reproduce but it's working fine on my end. May be I did not get exactly what you are doing. If you still can reproduce your issue, could you paste a full Java example?

Here is what I did:

```java
String source = "{\"query\":{\"match\":{\"gender\":\"male\"}}}";

// Testing without scroll
SearchResponse sr = client.prepareSearch(INDEX).setSource(source).get();
logger.info("{}", sr.toString());

// Testing with scroll
sr = client.prepareSearch(INDEX).setScroll("1m").setSource(source).get();
logger.info("{}", sr.toString());

// Both give expected results.
```

**Comment by kul** [comment] 2015-01-02 17:54
Hello @dadoonet ,

Thanks for testing this, what version are you using. I reported this for <= 1.3.2
Also please note that i am doing a setSearchType(SearchType.SCAN) for possibly large results.

Thanks

**Comment by dadoonet** [comment] 2015-01-12 09:56
Indeed. Setting `setSearchType(SearchType.SCAN)` give no results.

The test case I used did not use `SearchType.SCAN` because you mentioned that you would like to sort results, right? But scan type does not allow sorting. Did I misunderstand what you were looking for?

That said, you are right. I can reproduce what you saw. 

```java
SearchResponse sr = client().prepareSearch()
        .setScroll("1m")
        .setSource(source).get();
// Works fine
assertThat(sr.getHits().getHits().length, greaterThan(0));

sr = client().prepareSearch()
        .setSearchType(SearchType.SCAN)
        .setScroll("1m")
        .setSource(source).get();
// fails
assertThat(sr.getHits().getHits().length, greaterThan(0));
```

Working on it ATM.

**Comment by kul** [comment] 2015-01-12 10:08
@dadoonet ,
Do you think fixing this would then introduce ambiguity in API as you can pass a query which requests sorting but you do not get sorted results?

Any tips for scrolling large sorted results efficiently?
Thanks

**Comment by dadoonet** [comment] 2015-01-12 10:12
Actually, this what we should expect.

If you look at the documentation [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-scroll.html#scroll-scan), we wrote that:

> A scanning scroll request differs from a standard scroll request in three ways:
> * Sorting is disabled. Results are returned in the order they appear in the index.
> * Aggregations are not supported.
> * The response of the initial search request **will not contain any results in the hits array**. The first results will be returned by the first scroll request.
> * The size parameter controls the number of results per shard, not per request, so a size of 10 which hits 5 shards will return a maximum of 50 results per scroll request.

So what you need to do in Java is exactly the same thing as you need to do in REST:

```java
SearchResponse sr = client.prepareSearch(INDEX).setSearchType(SearchType.SCAN).setScroll("1m").setSource(source).get();

// Use sr.getScrollId() to iterate over results:
sr = client.prepareSearchScroll(sr.getScrollId()).setScroll(TimeValue.timeValueMinutes(2)).get();

// sr.getHits().getHits() will give you the first hits
```

Is it what you are looking for?

**Comment by dadoonet** [comment] 2015-01-12 10:17
> Any tips for scrolling large sorted results efficiently?

No. Not at this moment. You can not really scroll over very large sorted result set because it would require to allocate a lot of memory to sort all results per shard before sending the results.

See http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/scan-scroll.html

I think we can close this issue but feel free to reopen if I misunderstood what you are looking for and or add more comments.

**Closed by dadoonet** 2015-01-12 10:17 UTC
Labels: :Java API, feedback_needed

**Comment by kul** [comment] 2015-01-12 10:19
Yes exactly my point, enabling this would allow something like
```java
String source = "{\"query\":{..}, \"sort\": [...]}"
SearchResponse sr = client.prepareSearch(INDEX).setSearchType(SearchType.SCAN).setScroll("1m").setSource(source).get();
```
So we can pass a sort query but still not get sorted results. I am OK with this behavior too.

Thanks

**Comment by clintongormley** [comment] 2015-01-13 20:57
> No. Not at this moment. You can not really scroll over very large sorted result set because it would require to allocate a lot of memory to sort all results per shard before sending the results.


Actually, since v1.2(?) scrolling sorted results is much more efficient. You can now do deep scrolling of sorted queries, just don't use the `SCAN` search type.

**Comment by dadoonet** [comment] 2015-01-13 21:06
Thanks @clintongormley for correcting my answer.

**Comment by kul** [comment] 2015-01-14 03:47
Thanks @clintongormley and @dadoonet !
