### ISSUE TITLE
performance degredation between 0.90.5 and 1.4.1

### ISSUE THREAD

**Issue by Meidan** [elasticsearch/elasticsearch#9306] opened 2015-01-15 06:30 UTC
We're in the process of upgrading from 0.90.5 to 1.4.1 and we see a significant performance depredation in one of our queries.
https://gist.github.com/Meidan/f862103ff344baa48b0f#file-0-90-5-query
https://gist.github.com/Meidan/060dcc6f9d51d3f4ad0b#file-1-4-1-query

A short profiling session shows that the biggest difference is in the "nested native script" part of the query, which accounted for about 10% of the total search time in 0.90.5, but now it accounts for almost 50% in 1.4.1.
Most of that time is spent in org.elasticsearch.search.lookup.DocLookup.get(Object), which in turn calls a lot to org.elasticsearch.index.fielddata.ordinals.SinglePackedOrdinals$Docs.getOrd(int) and the script looks something like this:

```java
    private Map<String, Double> multipliers;
    public float runAsFloat() {
        ScriptDocValues.Strings term = (ScriptDocValues.Strings)doc().get("nested document term");
        ScriptDocValues.Doubles strength = (ScriptDocValues.Doubles) doc().get("nested document term strength");

        double score = multipliers.get(term.getValue()) * (1 + strength.getValue());
        return (float)score;
    }
```

Any idea on what changed between 0.90.5 and 1.4.1 that could have caused this?
Is there a better way of doing DocLookup that I'm missing?

**Comment by clintongormley** [comment] 2015-01-15 20:51
Hi @Meidan 

Could you provide the script?  

@jpountz any ideas here?

**Comment by Meidan** [comment] 2015-01-16 03:39
I've written down the script in the issue, and only changed some naming. I've also added the query gist. Anything else that I should add? Thanks!

**Comment by fasher** [comment] 2015-01-27 14:02
Hi, 
Any ideas? 
we are kind of puzzled were to go next with our upgrade now.

**Comment by jpountz** [comment] 2015-01-27 17:06
Hmm, I'm thinking that it could be https://github.com/elasticsearch/elasticsearch/pull/8591. Maybe you could help confirm by checking that you do not have the issue on 1.4.0?

We have an issue with scripts that we expect them both to be fast for search scripts, and safe at getting values (for instance fielddata fields assume it's ok to keep references onto previously created values while we would actually like to reuse them for speed).

**Comment by Meidan** [comment] 2015-01-28 16:28
I can confirm that 1.3.6 doesn't have the issue, I didn't check on 1.4.0 as it introduced a breaking change by removing AbstractFloatSearchScript.score().
So #8591 does seem as the most probable cause.

**Comment by jpountz** [comment] 2015-02-04 08:38
I just looked into it and the regression was actually introduced in #6908. ScriptDocValues.Strings have become slower due to unnecessary back and forth utf8 conversions. I'll open a pull request soon.

**Comment by jpountz** [comment] 2015-02-04 09:37
This will be fixed in the next release, thanks for the report!

**Closed** 2015-02-04 09:36 UTC
Labels: :Scripting

**Comment by Meidan** [comment] 2015-02-05 11:17
Thank you Adrien for the quick fix.
