### ISSUE TITLE
Failure to recover from 1-way network partition

### ISSUE THREAD

**Issue by magnhaug** [elasticsearch/elasticsearch#6469] opened 2014-06-11 16:22 UTC
After a 1-way network partition scenario, two nodes might be stuck in different opinions of which nodes are currently in the cluster.

I.e. with 5 nodes:
Node 1 sees node 1, 3 and 5. This is a RED cluster. 
Node 2 sees node 1, 2, 4 and 5. This is a GREEN cluster.
All of this according to the `nodes` endpoint.

The cluster is *stuck in this state*, even when every node could reach every other node (verified with curl on the es http port and binary port).

Some of these nodes give an NPE for the `_status` endpoint:
`{"error":"NullPointerException[null]","status":500}`

All nodes are configured to discover all the others through unicast.
Discovered on ES 0.90.13 on RHEL 6.5.

**Comment by bleskes** [comment] 2015-01-26 08:54
I'm going to close this assuming it is indeed a duplicate of #2488.

**Closed by bleskes** 2015-01-26 08:54 UTC
