### ISSUE TITLE
problem assigning shards during replicatoin

### ISSUE THREAD

**Issue by bhenderson** [elasticsearch/elasticsearch#9667] opened 2015-02-12 01:51 UTC
Hi, I have multiple indices (~100G each) that I'm trying to distribute across 4 data nodes. Because the index is largish, I have replication disabled during bulk inserts. When I try and increase the replication on one of the indices, it often gets stuck with 1 or 2 unassigned shards.

```
unassigned: [11]

shard allocation:
node0: [0,1,2,3,4,8,10,11]
node1: [0,1,2,3,4,5,6,7,8,9]
node2: [0,2,5,6,7,8,9,10,11]
node3: [1,3,4,5,6,7,8,9,10]
```

I have routing.allocation.total_shards_per_node set to 9 `number_of_shards * (number_of_replicas+1) / number_of_nodes`
I have number_of_shards arbitrarily set to 12.

The problem is that node0 has 8 shards, so it's the only node that can receive another shard, but it already has shard 11 so the final 11 shard remains unassigned indefinitely. The reason I set total_shards_per_node is because I'm trying to limit how often the cluster rebalances. I'm having stability problems anyway where a node will drop out.

thanks,

**Comment by clintongormley** [comment] 2015-02-12 12:53
Hi @bhenderson 

The problem is that `total_shards_per_node` is an absolute setting, rather than an heuristic (like the other allocation settings).  This is interfering with the allocation algorithm, blocking shards from being properly assigned.  If you remove it, you'll see that the shards balance themselves out.

Closing in favour of https://github.com/elasticsearch/elasticsearch/issues/9248

**Closed by clintongormley** 2015-02-12 12:53 UTC
