### ISSUE TITLE
StackOverFlow Exception during parsing of query

### ISSUE THREAD

**Issue by pisua** [elasticsearch/elasticsearch#9127] opened 2015-01-02 14:27 UTC
Hi, i encounter an issue during the parsing of the query. 
The error raise by elastic Search is : 
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StackOverflowError
	at java.util.BitSet.<init>(BitSet.java:154)
	at org.apache.lucene.util.automaton.Automaton.<init>(Automaton.java:75)
	at org.apache.lucene.util.automaton.Automata.makeString(Automata.java:273)
	at org.apache.lucene.util.automaton.RegExp.toAutomaton(RegExp.java:518)
	at org.apache.lucene.util.automaton.RegExp.findLeaves(RegExp.java:553)
	at org.apache.lucene.util.automaton.RegExp.findLeaves(RegExp.java:550)
	at org.apache.lucene.util.automaton.RegExp.findLeaves(RegExp.java:551)
	at org.apache.lucene.util.automaton.RegExp.findLeaves(RegExp.java:551)

it seems to fail during the analysis of the regular expression in the request in the lucent apache lucene part. I use the last version of elastic search 1.4.2. I don't encounter that issue with an old version of elastic 0.90.12. 
NB : the filter sent in the request contain or, and, and regular expression that is a quite large filter filter especially for the regular expression. let me know if you need the request send to understand that behavior and if it's a limitatio of lucene.

**Comment by clintongormley** [comment] 2015-01-02 15:07
Hi @pisua 

This sounds like an issue in Lucene itself. I suggest opening the issue there instead, and you'll definitely need to provide the regex itself.

Just before closing this issue here: @mikemccand could this exception be caused by the `max_determinized_states` change?

**Comment by rmuir** [comment] 2015-01-02 15:14
@clintongormley I'm not sure its that change, because that change is unreleased (it will be in the 1.5 release).

more likely its some oddity out of the refactoring in LUCENE-5752

**Comment by pisua** [comment] 2015-01-02 15:16
i'll open an issue about that exception in apache lucene side directly and let them see. thx for you quick reply

**Comment by rmuir** [comment] 2015-01-02 15:20
thank you... just from inspection, it may not be a lucene issue. I don't see what looks like infinite recursion in the stack trace. It may be caused by the fact that ES lowers the JVM stack size.

**Comment by pisua** [comment] 2015-01-02 15:42
i'll try by increasing stack size to see if it can solve the issue, because we use the default one. It can be a work around to resolve that issue if it works.
Plus, i've see the LUCENE-5752 and for me it's not really the same issue, so i've open a new one.

**Comment by pisua** [comment] 2015-01-05 09:51
i've raise an issue in lucene : LUCENE-6156 and also try to increase the stack size. 
The behavior with an increased stack size is better (that is normal) but it can still fail regarding the request and the activity of elastic search. 
i.e : if you index something and make a search another index or search again with a bigger regexp filter we still have the issue. 
Apache said there no issue in their side (you can have a look on  the lucene issue) and reply the issue should be in the elastic search side.
In my side, i think  i'll can find a work around with the stack size that is define to the JVM used by elastic search in order to don't have this kind of behavior.

**Comment by clintongormley** [comment] 2015-01-05 13:46
Closing in favour of #9135

**Closed by clintongormley** 2015-01-05 13:46 UTC
