### ISSUE TITLE
Cannot sort on scripted_metric aggregations

### ISSUE THREAD

**Issue by blingwang** [elasticsearch/elasticsearch#9620] opened 2015-02-10 01:07 UTC
I am currently using version 1.4.1. I created a scripted metric aggregations and want to sort the buckets by the scripted metric:
```
"aggs": {
        "rating_summary": {
            "terms": { "field": "_parent", "order": { "review_score_avg.value": "desc" } },
            "aggs": {
                "total_rating_count": { "sum": { "field": "rating_count" } },
                "total_rating_score": { "sum": { "field": "rating_total" } },
                "review_score_avg": {
                    "scripted_metric": {
                        "init_script" : "_agg['rating_count'] = []; _agg['rating_score'] = [];",
                        "map_script" : "_agg.rating_count.add(doc['rating_count'].value); _agg.rating_score.add(doc['rating_total'].value);", 
                        "combine_script" : "total_rating_count = 0; for (c in _agg.rating_count) { total_rating_count += c }; total_rating_score = 0; for (s in _agg.rating_score) { total_rating_score += s }; return [total_rating_score, total_rating_count];",
                        "reduce_script" : "total_score = 0; total_count = 0; for (a in _aggs) { def(score, count) = a; total_score += score; total_count += count; }; return (total_score + 0.0) / total_count;"
                    }
                }
            }
        }
    }
```
However, I got this error: 
AggregationExecutionException[Invalid terms aggregation order path [review_score_avg.value]. Terms buckets can only be sorted on a sub-aggregator path that is built out of zero or more single-bucket aggregations within the path and a final single-bucket or a metrics aggregation at the path end.

It seems the `ScriptedMetricAggregator extends MetricsAggregator`, but not `NumericMetricAggregator` in the current version, thus can not be used as an order path.

**Comment by colings86** [comment] 2015-02-10 14:59
This is indeed a limitation of the current implementation of script_metric aggregation. The issue is tracked here https://github.com/elasticsearch/elasticsearch/issues/8486. Closing in favour of that existing issue.

**Closed** 2015-02-10 17:05 UTC
