### ISSUE TITLE
SearchRequestBuilder.toString modifies the SearchRequestBuilder wiping any source set.

### ISSUE THREAD

**Issue by GaelTadh** [elasticsearch/elasticsearch#7317] opened 2014-08-18 15:30 UTC
If you use setSource on a SearchRequestBuilder and then call to string the SearchRequest will appear to be cleared. 

````
SearchRequestBuilder srb = client().prepareSearch().setSource("{\"query\":\"match\":{\"foo\":\"bar\"}}");
srb.execute().get();
```` 
Will execute the correct search, however 
````
SearchRequestBuilder srb = client().prepareSearch().setSource("{\"query\":\"match\":{\"foo\":\"bar\"}}");
logger.debug("About to execute [{}]",srb.toString());
srb.execute().get();
````
Will execute an empty search. 

The problem is that ````toString()```` calls ````internalBuilder()```` which calls ````sourceBuilder()```` 
````
    private SearchSourceBuilder sourceBuilder() {
        if (sourceBuilder == null) {
            sourceBuilder = new SearchSourceBuilder();
        }
        return sourceBuilder;
    }
````
Then when the ````SearchRequestBuilder.execute```` is called the request that was constructed via ````setSource```` is replaced by an empty sourceBuilder.

````
    @Override
    protected void doExecute(ActionListener<SearchResponse> listener) {
        if (sourceBuilder != null) {
            request.source(sourceBuilder());
        }
        client.search(request, listener);
    }
````

**Comment by javanna** [comment] 2015-02-27 21:37
Closing as duplicate of #5576

**Closed by javanna** 2015-02-27 21:37 UTC
Labels: bug
